### ISSUE TITLE
VS Code will not launch after changing "main" to "./glasscord.asar"

### ISSUE THREAD

**Issue by NathanBitTheMoon** [AryToNeX/Glasscord#35] opened 2020-06-04 13:40 UTC
After modifying the "package.json" file in `/usr/share/code/resources/app/`, VS code will no longer launch. I changed the "main" value form "./out/main" to "./glasscord.asar". This causes VS code to stop launching. Changing it back to "./out/main" fixes the issue. "glasscord.asar" has been placed in `/usr/share/code/resources/app`.

I have tried installing Glasstron through npm in the `/usr/share/code/resources/app/` directory, but this has had no effect. 

Running `code --verbose` in the shell, produced this
```
nbtm@glade:~$ code --verbose 
You are running a packaged Glasscord installation!
No write access to the installation folder! Glasscord won't auto update!
[Glasscord] [Linux] Module loaded!
[Glasscord] [CSSLoader] Module loaded!
Fetching featured Glasscord modules for application: Code
A JavaScript error occurred in the main process
Uncaught Exception:
undefined: undefined
[Glasscord Featured Modules] No featured modules available for this app.
```
- OS: Ubuntu 20.04 LTS
- DE: KDE Plasma
- VS Code Version: 1.45.1
- Glasscord version: 0.2

**Comment by AryToNeX** [comment] 2020-06-04 13:42
this is not a bug but a user error; in fact, you are supposed to clone the package.json to package.original.json to make that injection style work.

**Comment by NathanBitTheMoon** [comment] 2020-06-04 13:59
Doing this makes VS code launch, but the transparency and blur is not applied. I repeated the process, including re-downloading the files from your latest release. Running `code --verbose` produces a similar result, but without the JavaScript error. Can you suggest anything else I can try?

**Comment by AryToNeX** [comment] 2020-06-04 14:01
erm... did you read the readme carefully? Glasscord is not a theme but it is a tool. No transparency will happen unless you already have a theme that adds it to vscode.

**Comment by AryToNeX** [comment] 2020-06-04 14:04
closing this as it's user error

**Closed by AryToNeX** 2020-06-04 14:04 UTC
Labels: bug
